#!/usr/bin/env python

import os
import shutil
from diffusers import StableDiffusionDepth2ImgPipeline


model_id = "stabilityai/stable-diffusion-2-depth"
MODEL_CACHE = "diffusers-cache"
if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = StableDiffusionDepth2ImgPipeline.from_pretrained(
    model_id,
    cache_dir=MODEL_CACHE,
)
